name: Build Android

on:

  pull_request:

    branches-ignore:

      - ''
      
  push:

    branches-ignore:

      - ''

  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        arch: [ "aarch64" ]
      fail-fast: false

    name: "Build for ${{matrix.arch}}"

    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo apt update
          sudo apt install -y llvm libxrandr-dev libxxf86vm-dev libxcb-*-dev libx11-xcb-dev libxfixes-dev libdrm-dev libx11-dev
          pip3 install meson mako
          export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
          envsubst <android-${{matrix.arch}} >build-crossfile
          git clone --depth 1 https://github.com/alexvorxx/zink-xlib-termux 
          cd zink-xlib-termux && mkdir build-android
          meson setup "build-android" \
            --prefix=/tmp/mesa \
            --cross-file "../build-crossfile" \
            -Dplatforms=android \
            -Dplatform-sdk-version=33 \
            -Dllvm=false \
            -Dglx=xlib \
            -Ddri3=disabled \
            -Dopengl=true \
            -Dvulkan-drivers= \
            -Dgallium-drivers=zink \
            -Dbuildtype=release
          ninja -C "build-android" install
          cp /tmp/mesa
      - name: Upload libraries
        uses: actions/upload-artifact@v2
        with:
          name: mesa${{matrix.arch}}
          path: /tmp/mesa

